
name: Test
on: [push, pull_request]
jobs:
  Linux:
    name: Validate API spec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - uses: kong/setup-inso@v1
        with:
          inso-version: 2.4.0
      - name: Lint
        run: inso lint spec --ci
      - name: Run test suites
        run: inso run test --ci
      - name: Generate declarative config
        run: inso generate config --type declarative --ci
