
name: Test
on: [push]
jobs:
  Linux:
    name: Test API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - uses: kong/setup-inso@v1
        with:
          inso-version: 2.4.1
#       - name: Lint
#         run: inso lint spec "my-spec.yaml" --ci
      - name: Run test suites
        run: inso run test "test" --ci
      - name: Generate declarative config
        run: inso generate config "my-spec.yaml" --type declarative --ci
