name: Integration Test
on: [push]
jobs:
  Linux:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - uses: kong/setup-inso@v1
        with:
          inso-version: 2.4.0
#       - name: Lint
#         run: inso lint spec "my-spec.yaml" --ci
      - name: Run test suites
        run: inso run test "test"
